name: Test Build Environment

# Controls when the workflow will run
on: [push,workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ECHO:
    # The type of runner that the job will run on
    name: Test lvCICD
    runs-on: [self-hosted, lv2017]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: TestEnvironment
        id: lvEcho
        uses: NEVSTOP-LAB/lvEcho@main
        with:
          Operation: lvEcho
          Input1: "line1"
          Input2: "line2"
          Input3: "line3"

